apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/ansible/docker-compose.deploy.yml -o /home/ansible/manifests/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: payment
  name: payment
spec:
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5003
  selector:
    io.kompose.service: payment
