apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/ansible/docker-compose.deploy.yml -o /home/ansible/manifests/
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: waiter
  name: waiter
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: waiter
