---
name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer ansible et collections
        run: |
          pip install ansible ansible-lint
          ansible-galaxy collection install ansible.posix community.general

      - name: Lancer ansible-lint
        run: ansible-lint playbooks/ roles/

  bandit:
    name: Bandit SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Bandit
        run: pip install bandit

      - name: Lancer Bandit
        run: bandit -r app/ -ll

  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Lancer Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/python
            p/dockerfile
            p/ansible
  trivy:
    name: Trivy CVE Scan
    runs-on: ubuntu-latest
    steps:
     - name: Checkout du code
       uses: actions/checkout@v4

     - name: Builder les images avec docker compose
       run: docker compose -f app/docker-compose.yml build

     - name: Scanner customer
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: app-customer:latest
         format: table
         exit-code: '1'
         severity: HIGH,CRITICAL
         ignore-unfixed: true   # ← ignore les CVE sans fix disponible

     - name: Scanner waiter
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: app-waiter:latest
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL
          ignore-unfixed: true   # ← ignore les CVE sans fix disponible

     - name: Scanner kitchen
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: app-kitchen:latest
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL
          ignore-unfixed: true   # ← ignore les CVE sans fix disponible

     - name: Scanner payment
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: app-payment:latest
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL
          ignore-unfixed: true   # ← ignore les CVE sans fix disponible

     - name: Scanner reservation
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: app-reservation:latest
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL
          ignore-unfixed: true   # ← ignore les CVE sans fix disponible

  deploy:
    name: Deploy via Ansible
    runs-on: ubuntu-latest
    needs: [ansible-lint, bandit, semgrep, trivy]
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configurer la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM1_SSH_KEY }}" > ~/.ssh/id_ed25519_ci
          chmod 600 ~/.ssh/id_ed25519_ci
          ssh-keyscan ${{ secrets.VM1_HOST }} >> ~/.ssh/known_hosts

      - name: Git pull sur VM1
        run: |
          ssh -i ~/.ssh/id_ed25519_ci ${{ secrets.VM1_USER }}@${{ secrets.VM1_HOST }} \
          "cd ~/Ynov-k3s && git pull https://${{ secrets.GH_TOKEN }}@github.com/Heimlesss/Ynov-k3s.git"

      - name: Déployer le hardening CIS sur VM2
        run: |
          ssh -i ~/.ssh/id_ed25519_ci ${{ secrets.VM1_USER }}@${{ secrets.VM1_HOST }} \
          "cd ~/Ynov-k3s && ansible-playbook playbooks/harden.yml --private-key ~/.ssh/id_ed25519"

      - name: Déployer k3s sur VM2
        run: |
          ssh -i ~/.ssh/id_ed25519_ci ${{ secrets.VM1_USER }}@${{ secrets.VM1_HOST }} \
          "cd ~/Ynov-k3s && ansible-playbook playbooks/k3s.yml --private-key ~/.ssh/id_ed25519"